# Generated by Django 4.0.3 on 2022-03-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=500)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('liga', models.CharField(max_length=255)),
                ('founded', models.CharField(max_length=255)),
                ('Coach', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stadion', models.CharField(max_length=255)),
                ('webSait', models.CharField(max_length=255)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
