# Generated by Django 4.0.3 on 2022-03-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tournament_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament_table',
            name='games',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tournament_table',
            name='score',
            field=models.IntegerField(),
        ),
    ]
