# Generated by Django 4.0.3 on 2022-03-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_tournament_table_games_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament_table',
            name='id',
        ),
        migrations.AddField(
            model_name='tournament_table',
            name='_id',
            field=models.AutoField(default=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
